  release:
    types: [published]
name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.0.0)'
        required: true
        type: string
      name:
        description: 'Release title (optional)'
        required: false
        type: string
      body:
        description: 'Release notes (Markdown) (optional)'
        required: false
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build binaries (${{ matrix.goos }}-amd64)
    runs-on: ${{ matrix.os }}
    env:
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            ext: ""
          - os: macos-latest
            goos: darwin
            ext: ""
          - os: windows-latest
            goos: windows
            ext: ".exe"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.event_name == 'release' && github.event.release.tag_name || github.ref }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Run tests with coverage
        run: |
          go version
          go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
          flags: unittests
          fail_ci_if_error: false

      - name: Build
        run: |
          mkdir -p dist
          go build -ldflags "-s -w" -o "dist/webhook-catcher-cli_${{ matrix.goos }}_amd64${{ matrix.ext }}"
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.goos }}-amd64
          path: dist/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
          tag_name: ${{ github.event_name == 'push' && github.ref_name || github.event_name == 'release' && github.event.release.tag_name || inputs.tag }}
          name: ${{ github.event_name == 'push' && format('Release {0}', github.ref_name) || github.event_name == 'release' && format('Release {0}', github.event.release.tag_name) || (inputs.name || inputs.tag) }}
          body: ${{ inputs.body }}
          prerelease: ${{ inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
